application: 'hello-admin'
version: 51c

runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/icon/favicon.ico
  upload: static/icon/favicon\.ico
- url: /cron/.*
  script: handlers.urls.hello_admin_app
  login: admin
- url: .*
  script: handlers.urls.hello_admin_app
  login: required
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: pycrypto
  version: latest