application: 'hello-admin'
version: devjosef1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /cron/zendesk_daily_stasts
  script: handlers.urls.hello_admin_app
  login: admin
- url: /cron/sense_logs_purge
  script: handlers.urls.hello_admin_app
  login: admin
- url: /cron/application_logs_purge_queue
  script: handlers.urls.hello_admin_app
  login: admin
- url: /cron/application_logs_purge
  script: handlers.urls.hello_admin_app
  login: admin
- url: .*
  script: handlers.urls.hello_admin_app
  login: required
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: pycrypto
  version: latest